version: '3.8'

services:
  sora-webserver:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Azure OpenAI Configuration
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-08-01-preview}
      
      # Application Configuration
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_DEBUG=${APP_DEBUG:-false}
      
      # Job Management
      - MAX_CONCURRENT_JOBS=${MAX_CONCURRENT_JOBS:-10}
      - MAX_STORED_JOBS=${MAX_STORED_JOBS:-50}
      - JOB_CLEANUP_INTERVAL=${JOB_CLEANUP_INTERVAL:-3600}
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  default:
    driver: bridge